### ISSUE TITLE
mGerrit crashes [F-Droid build]

### ISSUE THREAD

**Issue by marmistrz** [JBirdVegas/external_jbirdvegas_mGerrit#61]
1. Tap the cloud icon
2. Tap the back button
3. The app crashes

```
10-21 17:44:25.672  2154  2154 E GerritTeamsHelper: File not found!
10-21 17:44:25.672  2154  2154 E GerritTeamsHelper: java.io.FileNotFoundException: /data/data/com.jbirdvegas.mgerrit/gerrits/AICP: open failed: EISDIR (Is a directory)
10-21 17:44:25.672  2154  2154 E GerritTeamsHelper:     at libcore.io.IoBridge.open(IoBridge.java:452)
10-21 17:44:25.672  2154  2154 E GerritTeamsHelper:     at java.io.FileInputStream.<init>(FileInputStream.java:76)
10-21 17:44:25.672  2154  2154 E GerritTeamsHelper:     at com.jbirdvegas.mgerrit.helpers.GerritTeamsHelper.readFileToGerritInstance(GerritTeamsHelper.java:177)
10-21 17:44:25.672  2154  2154 E GerritTeamsHelper:     at com.jbirdvegas.mgerrit.helpers.GerritTeamsHelper.getAllTeams(GerritTeamsHelper.java:148)
10-21 17:44:25.672  2154  2154 E GerritTeamsHelper:     at com.jbirdvegas.mgerrit.helpers.GerritTeamsHelper.<init>(GerritTeamsHelper.java:51)
10-21 17:44:25.672  2154  2154 E GerritTeamsHelper:     at com.jbirdvegas.mgerrit.activities.BaseDrawerActivity.addGerritsToDrawer(BaseDrawerActivity.java:228)
10-21 17:44:25.672  2154  2154 E GerritTeamsHelper:     at com.jbirdvegas.mgerrit.activities.BaseDrawerActivity.initNavigationDrawer(BaseDrawerActivity.java:172)
10-21 17:44:25.672  2154  2154 E GerritTeamsHelper:     at com.jbirdvegas.mgerrit.activities.GerritControllerActivity.onCreate(GerritControllerActivity.java:130)
10-21 17:44:25.672  2154  2154 E GerritTeamsHelper:     at android.app.Activity.performCreate(Activity.java:6251)
10-21 17:44:25.672  2154  2154 E GerritTeamsHelper:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
10-21 17:44:25.672  2154  2154 E GerritTeamsHelper:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2403)
10-21 17:44:25.672  2154  2154 E GerritTeamsHelper:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2510)
10-21 17:44:25.672  2154  2154 E GerritTeamsHelper:     at android.app.ActivityThread.-wrap11(ActivityThread.java)
10-21 17:44:25.672  2154  2154 E GerritTeamsHelper:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
10-21 17:44:25.672  2154  2154 E GerritTeamsHelper:     at android.os.Handler.dispatchMessage(Handler.java:102)
10-21 17:44:25.672  2154  2154 E GerritTeamsHelper:     at android.os.Looper.loop(Looper.java:148)
10-21 17:44:25.672  2154  2154 E GerritTeamsHelper:     at android.app.ActivityThread.main(ActivityThread.java:5461)
10-21 17:44:25.672  2154  2154 E GerritTeamsHelper:     at java.lang.reflect.Method.invoke(Native Method)
10-21 17:44:25.672  2154  2154 E GerritTeamsHelper:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
10-21 17:44:25.672  2154  2154 E GerritTeamsHelper:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
10-21 17:44:25.672  2154  2154 E GerritTeamsHelper:     at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
10-21 17:44:25.672  2154  2154 E GerritTeamsHelper: Caused by: android.system.ErrnoException: open failed: EISDIR (Is a directory)
10-21 17:44:25.672  2154  2154 E GerritTeamsHelper:     at libcore.io.IoBridge.open(IoBridge.java:442)
10-21 17:44:25.672  2154  2154 E GerritTeamsHelper:     ... 20 more
10-21 17:44:25.672  2154  2154 E GerritTeamsHelper: Failed to read stored Gerrit instance
10-21 17:44:25.672  2154  2154 E GerritTeamsHelper: org.json.JSONException: End of input at character 0 of 
10-21 17:44:25.672  2154  2154 E GerritTeamsHelper:     at org.json.JSONTokener.syntaxError(JSONTokener.java:449)
10-21 17:44:25.672  2154  2154 E GerritTeamsHelper:     at org.json.JSONTokener.nextValue(JSONTokener.java:97)
10-21 17:44:25.672  2154  2154 E GerritTeamsHelper:     at org.json.JSONObject.<init>(JSONObject.java:156)
10-21 17:44:25.672  2154  2154 E GerritTeamsHelper:     at org.json.JSONObject.<init>(JSONObject.java:173)
10-21 17:44:25.672  2154  2154 E GerritTeamsHelper:     at com.jbirdvegas.mgerrit.helpers.GerritTeamsHelper.readFileToGerritInstance(GerritTeamsHelper.java:203)
10-21 17:44:25.672  2154  2154 E GerritTeamsHelper:     at com.jbirdvegas.mgerrit.helpers.GerritTeamsHelper.getAllTeams(GerritTeamsHelper.java:148)
10-21 17:44:25.672  2154  2154 E GerritTeamsHelper:     at com.jbirdvegas.mgerrit.helpers.GerritTeamsHelper.<init>(GerritTeamsHelper.java:51)
10-21 17:44:25.672  2154  2154 E GerritTeamsHelper:     at com.jbirdvegas.mgerrit.activities.BaseDrawerActivity.addGerritsToDrawer(BaseDrawerActivity.java:228)
10-21 17:44:25.672  2154  2154 E GerritTeamsHelper:     at com.jbirdvegas.mgerrit.activities.BaseDrawerActivity.initNavigationDrawer(BaseDrawerActivity.java:172)
10-21 17:44:25.672  2154  2154 E GerritTeamsHelper:     at com.jbirdvegas.mgerrit.activities.GerritControllerActivity.onCreate(GerritControllerActivity.java:130)
10-21 17:44:25.672  2154  2154 E GerritTeamsHelper:     at android.app.Activity.performCreate(Activity.java:6251)
10-21 17:44:25.672  2154  2154 E GerritTeamsHelper:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
10-21 17:44:25.672  2154  2154 E GerritTeamsHelper:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2403)
10-21 17:44:25.672  2154  2154 E GerritTeamsHelper:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2510)
10-21 17:44:25.672  2154  2154 E GerritTeamsHelper:     at android.app.ActivityThread.-wrap11(ActivityThread.java)
10-21 17:44:25.672  2154  2154 E GerritTeamsHelper:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
10-21 17:44:25.672  2154  2154 E GerritTeamsHelper:     at android.os.Handler.dispatchMessage(Handler.java:102)
10-21 17:44:25.672  2154  2154 E GerritTeamsHelper:     at android.os.Looper.loop(Looper.java:148)
10-21 17:44:25.672  2154  2154 E GerritTeamsHelper:     at android.app.ActivityThread.main(ActivityThread.java:5461)
10-21 17:44:25.672  2154  2154 E GerritTeamsHelper:     at java.lang.reflect.Method.invoke(Native Method)
10-21 17:44:25.672  2154  2154 E GerritTeamsHelper:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
10-21 17:44:25.672  2154  2154 E GerritTeamsHelper:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
10-21 17:44:25.672  2154  2154 E GerritTeamsHelper:     at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
10-21 17:44:25.673  2154  2154 E GerritTeamsHelper: File not found!
10-21 17:44:25.673  2154  2154 E GerritTeamsHelper: java.io.FileNotFoundException: /data/data/com.jbirdvegas.mgerrit/gerrits/SIO2: open failed: EISDIR (Is a directory)
10-21 17:44:25.673  2154  2154 E GerritTeamsHelper:     at libcore.io.IoBridge.open(IoBridge.java:452)
10-21 17:44:25.673  2154  2154 E GerritTeamsHelper:     at java.io.FileInputStream.<init>(FileInputStream.java:76)
10-21 17:44:25.673  2154  2154 E GerritTeamsHelper:     at com.jbirdvegas.mgerrit.helpers.GerritTeamsHelper.readFileToGerritInstance(GerritTeamsHelper.java:177)
10-21 17:44:25.673  2154  2154 E GerritTeamsHelper:     at com.jbirdvegas.mgerrit.helpers.GerritTeamsHelper.getAllTeams(GerritTeamsHelper.java:148)
10-21 17:44:25.673  2154  2154 E GerritTeamsHelper:     at com.jbirdvegas.mgerrit.helpers.GerritTeamsHelper.<init>(GerritTeamsHelper.java:51)
10-21 17:44:25.673  2154  2154 E GerritTeamsHelper:     at com.jbirdvegas.mgerrit.activities.BaseDrawerActivity.addGerritsToDrawer(BaseDrawerActivity.java:228)
10-21 17:44:25.673  2154  2154 E GerritTeamsHelper:     at com.jbirdvegas.mgerrit.activities.BaseDrawerActivity.initNavigationDrawer(BaseDrawerActivity.java:172)
10-21 17:44:25.673  2154  2154 E GerritTeamsHelper:     at com.jbirdvegas.mgerrit.activities.GerritControllerActivity.onCreate(GerritControllerActivity.java:130)
10-21 17:44:25.673  2154  2154 E GerritTeamsHelper:     at android.app.Activity.performCreate(Activity.java:6251)
10-21 17:44:25.673  2154  2154 E GerritTeamsHelper:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
10-21 17:44:25.673  2154  2154 E GerritTeamsHelper:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2403)
10-21 17:44:25.673  2154  2154 E GerritTeamsHelper:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2510)
10-21 17:44:25.673  2154  2154 E GerritTeamsHelper:     at android.app.ActivityThread.-wrap11(ActivityThread.java)
10-21 17:44:25.673  2154  2154 E GerritTeamsHelper:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
10-21 17:44:25.673  2154  2154 E GerritTeamsHelper:     at android.os.Handler.dispatchMessage(Handler.java:102)
10-21 17:44:25.673  2154  2154 E GerritTeamsHelper:     at android.os.Looper.loop(Looper.java:148)
10-21 17:44:25.673  2154  2154 E GerritTeamsHelper:     at android.app.ActivityThread.main(ActivityThread.java:5461)
10-21 17:44:25.673  2154  2154 E GerritTeamsHelper:     at java.lang.reflect.Method.invoke(Native Method)
10-21 17:44:25.673  2154  2154 E GerritTeamsHelper:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
10-21 17:44:25.673  2154  2154 E GerritTeamsHelper:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
10-21 17:44:25.673  2154  2154 E GerritTeamsHelper:     at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
10-21 17:44:25.673  2154  2154 E GerritTeamsHelper: Caused by: android.system.ErrnoException: open failed: EISDIR (Is a directory)
10-21 17:44:25.673  2154  2154 E GerritTeamsHelper:     at libcore.io.IoBridge.open(IoBridge.java:442)
10-21 17:44:25.673  2154  2154 E GerritTeamsHelper:     ... 20 more
10-21 17:44:25.674  2154  2154 E GerritTeamsHelper: Failed to read stored Gerrit instance
10-21 17:44:25.674  2154  2154 E GerritTeamsHelper: org.json.JSONException: End of input at character 0 of 
10-21 17:44:25.674  2154  2154 E GerritTeamsHelper:     at org.json.JSONTokener.syntaxError(JSONTokener.java:449)
10-21 17:44:25.674  2154  2154 E GerritTeamsHelper:     at org.json.JSONTokener.nextValue(JSONTokener.java:97)
10-21 17:44:25.674  2154  2154 E GerritTeamsHelper:     at org.json.JSONObject.<init>(JSONObject.java:156)
10-21 17:44:25.674  2154  2154 E GerritTeamsHelper:     at org.json.JSONObject.<init>(JSONObject.java:173)
10-21 17:44:25.674  2154  2154 E GerritTeamsHelper:     at com.jbirdvegas.mgerrit.helpers.GerritTeamsHelper.readFileToGerritInstance(GerritTeamsHelper.java:203)
10-21 17:44:25.674  2154  2154 E GerritTeamsHelper:     at com.jbirdvegas.mgerrit.helpers.GerritTeamsHelper.getAllTeams(GerritTeamsHelper.java:148)
10-21 17:44:25.674  2154  2154 E GerritTeamsHelper:     at com.jbirdvegas.mgerrit.helpers.GerritTeamsHelper.<init>(GerritTeamsHelper.java:51)
10-21 17:44:25.674  2154  2154 E GerritTeamsHelper:     at com.jbirdvegas.mgerrit.activities.BaseDrawerActivity.addGerritsToDrawer(BaseDrawerActivity.java:228)
10-21 17:44:25.674  2154  2154 E GerritTeamsHelper:     at com.jbirdvegas.mgerrit.activities.BaseDrawerActivity.initNavigationDrawer(BaseDrawerActivity.java:172)
10-21 17:44:25.674  2154  2154 E GerritTeamsHelper:     at com.jbirdvegas.mgerrit.activities.GerritControllerActivity.onCreate(GerritControllerActivity.java:130)
10-21 17:44:25.674  2154  2154 E GerritTeamsHelper:     at android.app.Activity.performCreate(Activity.java:6251)
10-21 17:44:25.674  2154  2154 E GerritTeamsHelper:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
10-21 17:44:25.674  2154  2154 E GerritTeamsHelper:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2403)
10-21 17:44:25.674  2154  2154 E GerritTeamsHelper:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2510)
10-21 17:44:25.674  2154  2154 E GerritTeamsHelper:     at android.app.ActivityThread.-wrap11(ActivityThread.java)
10-21 17:44:25.674  2154  2154 E GerritTeamsHelper:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
10-21 17:44:25.674  2154  2154 E GerritTeamsHelper:     at android.os.Handler.dispatchMessage(Handler.java:102)
10-21 17:44:25.674  2154  2154 E GerritTeamsHelper:     at android.os.Looper.loop(Looper.java:148)
10-21 17:44:25.674  2154  2154 E GerritTeamsHelper:     at android.app.ActivityThread.main(ActivityThread.java:5461)
10-21 17:44:25.674  2154  2154 E GerritTeamsHelper:     at java.lang.reflect.Method.invoke(Native Method)
10-21 17:44:25.674  2154  2154 E GerritTeamsHelper:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
10-21 17:44:25.674  2154  2154 E GerritTeamsHelper:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
10-21 17:44:25.674  2154  2154 E GerritTeamsHelper:     at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
10-21 17:44:25.802  1367  2626 I ActivityManager: START u0 {act=com.android.systemui.recents.SHOW_RECENTS flg=0x10804000 cmp=com.android.systemui/.recents.RecentsActivity} from uid 10028 on display 0
10-21 17:44:25.839  2154  2154 D AndroidRuntime: Shutting down VM
10-21 17:44:25.843  2154  2154 E AndroidRuntime: FATAL EXCEPTION: main
10-21 17:44:25.843  2154  2154 E AndroidRuntime: Process: com.jbirdvegas.mgerrit, PID: 2154
10-21 17:44:25.843  2154  2154 E AndroidRuntime: Theme: themes:{default=overlay:system, iconPack:system, fontPkg:system, com.android.systemui=overlay:system, com.android.systemui.navbar=overlay:system}
10-21 17:44:25.843  2154  2154 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.jbirdvegas.mgerrit/com.jbirdvegas.mgerrit.activities.GerritControllerActivity}: java.lang.RuntimeException: Parcel android.os.Parcel@18b1d68: Unmarshalling unknown type code 28 at offset 1396
10-21 17:44:25.843  2154  2154 E AndroidRuntime:    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2450)
10-21 17:44:25.843  2154  2154 E AndroidRuntime:    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2510)
10-21 17:44:25.843  2154  2154 E AndroidRuntime:    at android.app.ActivityThread.-wrap11(ActivityThread.java)
10-21 17:44:25.843  2154  2154 E AndroidRuntime:    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
10-21 17:44:25.843  2154  2154 E AndroidRuntime:    at android.os.Handler.dispatchMessage(Handler.java:102)
10-21 17:44:25.843  2154  2154 E AndroidRuntime:    at android.os.Looper.loop(Looper.java:148)
10-21 17:44:25.843  2154  2154 E AndroidRuntime:    at android.app.ActivityThread.main(ActivityThread.java:5461)
10-21 17:44:25.843  2154  2154 E AndroidRuntime:    at java.lang.reflect.Method.invoke(Native Method)
10-21 17:44:25.843  2154  2154 E AndroidRuntime:    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
10-21 17:44:25.843  2154  2154 E AndroidRuntime:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
10-21 17:44:25.843  2154  2154 E AndroidRuntime:    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
10-21 17:44:25.843  2154  2154 E AndroidRuntime: Caused by: java.lang.RuntimeException: Parcel android.os.Parcel@18b1d68: Unmarshalling unknown type code 28 at offset 1396
10-21 17:44:25.843  2154  2154 E AndroidRuntime:    at android.os.Parcel.readValue(Parcel.java:2340)
10-21 17:44:25.843  2154  2154 E AndroidRuntime:    at android.os.Parcel.readSparseArrayInternal(Parcel.java:2675)
10-21 17:44:25.843  2154  2154 E AndroidRuntime:    at android.os.Parcel.readSparseArray(Parcel.java:1967)
10-21 17:44:25.843  2154  2154 E AndroidRuntime:    at android.os.Parcel.readValue(Parcel.java:2321)
10-21 17:44:25.843  2154  2154 E AndroidRuntime:    at android.os.Parcel.readArrayMapInternal(Parcel.java:2614)
10-21 17:44:25.843  2154  2154 E AndroidRuntime:    at android.os.BaseBundle.unparcel(BaseBundle.java:221)
10-21 17:44:25.843  2154  2154 E AndroidRuntime:    at android.os.Bundle.getSparseParcelableArray(Bundle.java:856)
10-21 17:44:25.843  2154  2154 E AndroidRuntime:    at com.android.internal.policy.PhoneWindow.restoreHierarchyState(PhoneWindow.java:2083)
10-21 17:44:25.843  2154  2154 E AndroidRuntime:    at android.app.Activity.onRestoreInstanceState(Activity.java:1008)
10-21 17:44:25.843  2154  2154 E AndroidRuntime:    at android.app.Activity.performRestoreInstanceState(Activity.java:963)
10-21 17:44:25.843  2154  2154 E AndroidRuntime:    at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1164)
10-21 17:44:25.843  2154  2154 E AndroidRuntime:    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2423)
10-21 17:44:25.843  2154  2154 E AndroidRuntime:    ... 10 more
10-21 17:44:25.844  1367  2626 W ActivityManager:   Force finishing activity com.jbirdvegas.mgerrit/.activities.GerritControllerActivity
```

**Comment by p4r4n01d** [comment]
That error has been fixed (see: https://github.com/JBirdVegas/external_jbirdvegas_mGerrit/commit/2e717f73bbd29e55dd80e949c95d5ae759fa96fa). Please upgrade mGerrit to the latest version and remove any folders under: /data/data/com.jbirdvegas.mgerrit/gerrits/ (this can be done by clearing data) then try again.

**Comment by nailyk-fr** [comment]
Confirmed fixed on [2.111.90](https://releases.nailyk.fr/repo/)

**Comment by marmistrz** [comment]
If I encounter that problem with a more recent version, I'll reopen.

**Comment by nailyk-fr** [comment]
Yes, still present on : HEAD is now at 6a74324 Release: update version to: 2.111.90
4 days ago: https://releases.nailyk.fr/jenkins/job/F-Droid/job/k_mGerrit/31/console
APK is here: https://releases.nailyk.fr/repo/

Problem to setup custom gerrit instance is still here too.
